# GitOps values for notebook-controller.

# Labels to add to all resources
commonLabels:
  app: notebook-controller

image:
  repository: ghcr.io/teknoir/notebook-controller
  tag: teknoir-cloud-20260413-055422
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-token

serviceAccount:
  name: notebook-controller-service-account

addFsGroup: "true"

parameters:
  USE_ISTIO: "true"
  ISTIO_GATEWAY: istio-system/teknoir-gateway
  POD_LABELS: gcp-cred-secret=user-gcp-sa,gcp-cred-secret-filename=user-gcp-sa.json
  project-id: teknoir
  domain: teknoir.online
