apiVersion: v2
name: auth
description: KeycloakX, OAuth2/OIDC, and Istio auth GitOps
type: application
version: 0.0.3
appVersion: "0.1.0"
dependencies:
  - name: keycloakx
    alias: keycloak
    version: 7.1.9
    repository: "https://codecentric.github.io/helm-charts"
    condition: keycloak.enabled
