{{- $domain := .Values.domain | default (index .Values "global" "domain") | default "teknoir.online" -}}
{{- $namespace := .Values.namespace | default .Release.Namespace -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
  namespace: {{ $namespace }}
spec:
  hosts:
    - {{ printf "auth.%s" $domain | quote }}
  gateways:
    - istio-system/teknoir-gateway
  http:
    - name: keycloak
      route:
        - destination:
            host: keycloak-http.{{ $namespace }}.svc.cluster.local
            port:
              number: 80
