{{- $namespace := .Values.namespace | default .Release.Namespace -}}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: keycloak-db-allow
  namespace: {{ $namespace }}
spec:
  selector:
    matchLabels:
      app: keycloak-db
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - {{ $namespace }}

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: keycloak-allow-ingress
  namespace: {{ $namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/istio-system/sa/istio-ingressgateway"
    - from:
        - source:
            namespaces:
              - "teknoir-system"
