apiVersion: v2
name: aws-eks
description: AWS and EKS addons
type: application
version: 0.0.1
appVersion: "0.1.0"
dependencies:
  - name: aws-load-balancer-controller
    version: 3.2.2
    repository: https://aws.github.io/eks-charts
