# GitOps values for backstage

# Parameters from params.env
config:
  domain: "teknoir.online"
  logLevel: info
  prometheusUrl: http://prometheus.__NAMESPACE__.svc.cluster.local:80

# Backstage frontend deployment
backstage:
  replicas: 1
  image: ghcr.io/teknoir/backstage-app:latest
  imagePullPolicy: Always
  imagePullSecrets:
    - name: ghcr-token
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

# Backstage API deployment
backstageApi:
  replicas: 1
  image: ghcr.io/teknoir/backstage:latest
  imagePullPolicy: Always
  imagePullSecrets:
    - name: ghcr-token
  nodeOptions: '--max-old-space-size=8192'
  podSecurityContext:
    fsGroup: 1000
  containerSecurityContext:
    runAsUser: 1000
  secrets:
    postgresSecretName: backstage-postgres-secrets
    keycloakSecretName: backstage-keycloak-secrets
    authSecretsName: backstage-auth-secrets
  googleApplicationCredentials: '/app/secrets/admin-credentials.json'
  githubAppSecretPath: /app/secrets/backstage-github-credentials.yaml
  resources:
    limits:
      cpu: "2"
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 1Gi

# PostgreSQL database configuration
postgres:
  replicas: 1
  image: postgres:17-alpine
  imagePullPolicy: Always
  storage: 10Gi
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi
  exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi

# Istio configuration (optional)
istio:
  gateway: istio-system/teknoir-gateway
  ingressNamespace: istio-system
  ingressServiceAccount: istio-ingressgateway
  metricsNamespace: monitoring-system
  jwt:
    fromHeaders:
      - name: X-Forwarded-Access-Token
      - name: X-Auth-Request-Access-Token
