{{- $namespace := .Values.namespace | default .Release.Namespace -}}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: argocd-server-mtls
  namespace: {{ $namespace }}
spec:
  host: "argocd-server.{{ $namespace }}.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
