# GitOps values for profile-controller.

replicaCount: 1

image:
  repository: ghcr.io/teknoir/profile-controller
  tag: teknoir-cloud
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-token

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceAccount:
  # Annotations to add to the service account
  annotations: {}


config:
  admin: "anders.aslund@teknoir.ai"
  workloadIdentity: ""
  userIdHeader: "X-Auth-Request-Email"
  userIdPrefix: ""
  projectId: "teknoir"
  domain: "teknoir.online"
  domainPrefix: ""
  region: "us-central1"
  dnsZone: "teknoir-online"
  istioRevision: "1.29.0"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
