---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ca.issuerName | default "teknoir-ca" }}
spec:
  ca:
    secretName: {{ .Values.ca.secretName | default "teknoir-root-ca" }}
