---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-eks
spec:
  destination:
    namespace: teknoir-system
    server: https://kubernetes.default.svc
  source:
    path: charts/aws-eks
    repoURL: https://github.com/teknoir/platform-applications-gitops
    targetRevision: {{ .Values.project }}
  sources: [ ]
  project: {{ .Values.project }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
