---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  source:
    repoURL: harbor.teknoir.local/teknoir
    chart: istio
    targetRevision: 0.0.1
  project: {{ .Values.project }}
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
      enabled: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/0/failurePolicy
