---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  destination:
    namespace: teknoir-system
    server: https://kubernetes.default.svc
  source:
    path: charts/monitoring
    repoURL: https://github.com/teknoir/platform-applications-gitops
    targetRevision: {{ .Values.project }}
  sources: [ ]
  project: {{ .Values.project }}
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
      enabled: true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: monitoring-grafana
      jsonPointers:
        - /data
        - /stringData
    - group: "apps"
      kind: Deployment
      name: monitoring-grafana
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
        - /spec/template/metadata/annotations/checksum~1sc-dashboard-provider-config
        - /spec/template/metadata/annotations/checksum~1dashboards-json-config
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: monitoring-kube-prome-admission
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: monitoring-kube-prome-admission
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
