# Values for cert-manager
domain: "teknoir.cloud"

cert-manager:
  fullnameOverride: cert-manager
  crds:
    enabled: true

godaddy-webhook:
  fullnameOverride: godaddy-webhook
  groupName: acme.webhook.godaddy.com

cert-manager-webhook-loopia:
  fullnameOverride: cert-manager-webhook-loopia
  groupName: acme.webhook.loopia.com
