# Values for cert-manager
domain: "teknoir.online"

cert-manager:
  fullnameOverride: cert-manager
  crds:
    enabled: true
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      memory: "1Gi"
  webhook:
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        memory: "1Gi"
  cainjector:
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        memory: "1Gi"

godaddy-webhook:
  fullnameOverride: godaddy-webhook
  groupName: acme.webhook.godaddy.com
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      memory: "1Gi"

cert-manager-webhook-loopia:
  fullnameOverride: cert-manager-webhook-loopia
  groupName: acme.webhook.loopia.com
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      memory: "1Gi"
